name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello, Its me"
      - name: Print Date
        run: echo date
      - name: Bye Bye !!!
        run: echo "Bye Bye"
    
